# Generated by Django 3.0.3 on 2020-02-16 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=10, verbose_name='Phone number')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50, verbose_name='Gender')),
                ('dob', models.DateField(verbose_name='Date of birth')),
                ('address', models.TextField(verbose_name='Address')),
                ('aadhar_no', models.IntegerField(verbose_name='Aadhar Number')),
                ('aadhar_pic', models.ImageField(upload_to='%y/%m/%d', verbose_name='Aadhar image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
